import type { Metadata } from "next";
import "../libs/index.scss";
import "../libs/reset.scss";
import "../libs/vars.scss";
import "../libs/App.scss";
import { Footer } from "@/components";
// import { useScrollToTop } from "@/hooks";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className="app">
					<main>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
